const DATA = {
    employee: {
      name: 'Fulan bin Titan',
      position: 'Full Stack Developer',
      email: 'sample.address@supermail.sh',
      image: 'https://thispersondoesnotexist.com/',
      biodata: {
        profile: 'A biodegradable employee, since i am a human :)',
        placeOfBirth: 'Jakarta',
        dateOfBirth: 'xx May 2001',
        gender: 'Male',
        religion: 'Moslem',
        language: 'English, Indonesian',
      },
    },
    histories: {
      employment: [
        {
          employer: 'Sample',
          position: 'Sample',
          from: 'June 2021',
          to: 'July 2024',
        },
        {
          employer: 'Sample',
          position: 'Sample',
          from: 'June 2021',
          to: 'July 2024',
        },
        {
          employer: 'Sample',
          position: 'Sample',
          from: 'June 2021',
          to: 'July 2024',
        },
        {
          employer: 'Sample',
          position: 'Sample',
          from: 'June 2021',
          to: 'July 2024',
        },
        {
          employer: 'Sample',
          position: 'Sample',
          from: 'June 2021',
          to: 'July 2024',
        },
      ],
      certification: [
        {
          title: 'Sample',
          provider: 'Sample',
          date: 'December 2024',
          duration: '5 Years',
          certificate: 'Sample',
        },
        {
          title: 'Sample',
          provider: 'Sample',
          date: 'December 2024',
          duration: '5 Years',
          certificate: 'Sample',
        },
        {
          title: 'Sample',
          provider: 'Sample',
          date: 'December 2024',
          duration: '5 Years',
          certificate: 'Sample',
        },
      ],
      education: [
        {
          school: 'Sample',
          degree: 'Sample',
          subject: 'Sample',
          from: '2020',
          to: '2024',
        },
        {
          school: 'Sample',
          degree: 'Sample',
          subject: 'Sample',
          from: '2020',
          to: '2024',
        },
      ],
      project: [
        {
          projectName: 'Sample',
          role: 'Sample',
          from: 'June 2000',
          to: 'December 2024',
          customer: 'Sample',
          projectDescription: 'Sample',
          technicalInformation: 'Sample',
          jobDescription: 'Sample',
        },
        {
          projectName: 'Sample',
          role: 'Sample',
          from: 'June 2000',
          to: 'December 2024',
          customer: 'Sample',
          projectDescription: 'Sample',
          technicalInformation: 'Sample',
          jobDescription: 'Sample',
        },
        {
          projectName: 'Sample',
          role: 'Sample',
          from: 'June 2000',
          to: 'December 2024',
          customer: 'Sample',
          projectDescription: 'Sample',
          technicalInformation: 'Sample',
          jobDescription: 'Sample',
        },
        {
          projectName: 'Sample',
          role: 'Sample',
          from: 'June 2000',
          to: 'December 2024',
          customer: 'Sample',
          projectDescription: 'Sample',
          technicalInformation: 'Sample',
          jobDescription: 'Sample',
        },
        {
          projectName: 'Sample',
          role: 'Sample',
          from: 'June 2000',
          to: 'December 2024',
          customer: 'Sample',
          projectDescription: 'Sample',
          technicalInformation: 'Sample',
          jobDescription: 'Sample',
        },
        {
          projectName: 'Sample',
          role: 'Sample',
          from: 'June 2000',
          to: 'December 2024',
          customer: 'Sample',
          projectDescription: 'Sample',
          technicalInformation: 'Sample',
          jobDescription: 'Sample',
        },
        {
          projectName: 'Sample',
          role: 'Sample',
          from: 'June 2000',
          to: 'December 2024',
          customer: 'Sample',
          projectDescription: 'Sample',
          technicalInformation: 'Sample',
          jobDescription: 'Sample',
        },
      ],
    },
  };
export default DATA;
